### ISSUE TITLE
Помилка відображення служб

### ISSUE THREAD

**Issue by Brazilianian** [dmytro-ustynov/ItemsManager#1]
![IMG_20240730_130322_589.jpg](https://github.com/user-attachments/assets/465ef9fd-47a0-491b-bd78-9f9f4089ec6a)

![IMG_20240730_130433_439.jpg](https://github.com/user-attachments/assets/d68642f5-0b25-4993-85cb-123e0e1e15e4)

**Comment by dmytro-ustynov** [comment]
This bug already fixed
